### ISSUE TITLE
sub_开头的函数好像不能恢复

### ISSUE THREAD

**Issue by HJaycee** [tobefuturer/restore-symbol#11]
你好，我使用了你的restore-symbol，发现sub_开头的函数名还是没有恢复，两个dylib的大小是一样的，请指教一下！

**Comment by tobefuturer** [comment]
能恢复的符号 为oc函数（全部），oc的block（个别遗漏）。
sub_开头的函数，是c函数部分，相关信息已经被strip掉，无法恢复。

**Comment by HJaycee** [comment]
好的，多谢解答！
