### ISSUE TITLE
从json 文件恢复 ，报错，提示 not found in the image

### ISSUE THREAD

**Issue by hellofrida** [tobefuturer/restore-symbol#14]
=========== Start =============
Scan OC method in mach-o-file.
Scan OC method finish.
Parse symbols in json file.
Parse finish.
2017-12-27 21:07:14.885 restore-symbol[62865:724524] Address(1c5001) not found in the image

**Comment by tobefuturer** [comment]
方便的话 发一下macho和json文件， 我看一下

**Comment by Jifeng2015** [comment]
提示这个错误（Restore-symbol supports armv7 and arm64 archtecture, but not support fat file. Please use lipo to thin the image file first.）我用的就是pp助手下载的越狱版ipa，怎么办 @tobefuturer

**Comment by tobefuturer** [comment]
那句提示就是原因

**Comment by Jifeng2015** [comment]
我知道啊，可是我要用哪个image file 呢？不就是跟ipa解压出来的Mach-O文件的么？好比Wechat.app/WeChat,难道不是这个文件吗？

**Comment by Jifeng2015** [comment]
我知道啊，可是我要用哪个image file 呢？不就是跟ipa解压出来的Mach-O文件的么？好比Wechat.app/WeChat,难道不是这个文件吗？ @tobefuturer

**Comment by Jifeng2015** [comment]
![image](https://user-images.githubusercontent.com/11371532/37700443-7ce23646-2d26-11e8-8b6e-fe7d14b14966.png)
好像只有fat file！？ @tobefuturer

**Comment by Jifeng2015** [comment]
大神回答下咯，这个./restore-symbol /pathto/origin_mach_o_file -o /pathto/mach_o_with_symbol  的origin_mach_o_file竟然是哪个啊？ @tobefuturer

**Comment by Jifeng2015** [comment]
多谢大神的沉默，我找到方法了，要先做瘦身处理，一开始没懂lipo指令，
步骤1：先瘦身
lipo Wechat -thin arm64 -output Wechatthin
步骤2：再导出
./restore-symbol WeChatthin -o WeChat_with_symbol

**Comment by tobefuturer** [comment]
bingo，答对啦，基础的东西最好自己先google查下
