### ISSUE TITLE
导入符号后无法识别arch

### ISSUE THREAD

**Issue by Goosoul** [tobefuturer/restore-symbol#17]
我的可执行文件只有arm64一个arch，不是FAT。烧机器的时候Xcode报cpu无法识别的错误，我用MachOView看了一下，arch是(???)。

**Comment by tobefuturer** [comment]
能发下原始文件看下吗

**Comment by Goosoul** [comment]
我是用Xcode run的脚本，类似以下：
```
dylib=$1

lipo -thin arm64 $dylib -o $dylib

restore-symbol $dylib -o $dylib"-with-symbols"

cp $dylib"-with-symbols" $dylib

rm $dylib"-with-symbols"
```
但我在尝试提取示例时发现无法复现，只是在运行工程时出现了
![image](https://user-images.githubusercontent.com/13354302/37575616-0ac5dfbe-2b63-11e8-93bf-1c6ec94132cb.png)
异常的地方在 __00109B50 CPU SubType__ 
正常情况应是 __00000000 CPU SubType__

上传又抽风了，暂时无法提供

**Comment by tobefuturer** [comment]
有点诡异。。。看其他数据没啥问题，就这一个字段出问题了，你试试看不要每次都rm掉那个-with-symbol文件，把他copy到某个路径下，如果出问题了 相当于一个现场

**Comment by Goosoul** [comment]
@tobefuturer 试过了，-with-symbol那个文件就已经出错了。目前来看，armv7已经没多大空间了，只需要使用arm64，所有暂时修改了源码，最后输出的时候强制修改range(8,4) => 0x00000000。输出就正常了。

**Comment by Goosoul** [comment]
@tobefuturer 我在源码的这个地方
```
command -> dataoff = final_offset;
```
发现那个标识位（文件的第3个32bit）被修改了从0x00000000修改成其他东西了

**Comment by Goosoul** [comment]
我找到错误的原因了，是因为没有签名，出错的代码如下：
```
struct linkedit_data_command *command = (struct linkedit_data_command *)((char *)outData.mutableBytes + codesignature.commandOffset);
uint32_t tmp_offset =  command -> dataoff + increase_size_all_without_padding;
uint32_t final_offset = vm_addr_round(tmp_offset, 16);
        
string_table_padding = final_offset - tmp_offset;
command -> dataoff = final_offset;
```
当codesignature.commandOffset == 0时，command -> dataoff刚好是文件的第三个32bit，也就是那个出错标识符的位置
