### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by jiadeYu** [tobefuturer/restore-symbol#19]
Showing All Messages
No such file or directory: '/Users/jiadeyu/Desktop/540Crash/restore-symbol-master/class-dump/Source/CDStructureTable.m'

**Comment by jiadeYu** [comment]
class-dump 是空的

**Comment by tobefuturer** [comment]
git clone --recursive https://github.com/tobefuturer/restore-symbol.git
参数漏了吧
