### ISSUE TITLE
如何用 Xcode 连上 app 进行调试的呢？

### ISSUE THREAD

**Issue by qiaoxueshi** [tobefuturer/restore-symbol#2]
请问在你的这片文章中，如何用 Xcode 连上 app 进行调试的呢？

http://mp.weixin.qq.com/s?__biz=MjM5NTIyNTUyMQ==&mid=2709545175&idx=1&sn=1c080685fabf2f24269c6e544e9213d7&scene=23&srcid=0829sV2pk0n22Qt9LfiRPPsO#rd

**Comment by feikang** [comment]
这个同问，我尝试过重签名，使用的是开发证书，但是运行不起来啊。望大神不吝赐教。

**Comment by DSKcpp** [comment]
@qiaoxueshi @feikang  
http://url.cn/2Brnwtn
主要是编写 shell 脚本，在 Xcode Run 自己的项目时把目标 .app 文件替换到当前项目下。

**Comment by tobefuturer** [comment]
嗯 这是我师弟的文章 跟着里面一步步做就可以了 不过支付宝有一定的防护措施 要稍微手动处理下 
http://mp.weixin.qq.com/s?__biz=MjM5NTIyNTUyMQ==&mid=456678545&idx=1&sn=70f5784541fc15d5af252a15a400900d&scene=1&srcid=0829jK509F5Vb9FmfD0RghUn#rd

**Comment by qiaoxueshi** [comment]
@tobefuturer 多谢
