### ISSUE TITLE
block符号的恢复步骤

### ISSUE THREAD

**Issue by kobe1941** [tobefuturer/restore-symbol#21]
请问下，block符号的恢复步骤也是拿最初的二进制文件嘛，而不是已经恢复了OC符号的二进制来作为下一步的输入？

**Comment by kobe1941** [comment]
提取block符号好像失败了，收到两个警告：
2018-08-28 18:23:50.452 restore-symbol[22154:403912] Warning: Parsing method types failed, collectAllRegisterInfos:context:needCheckFirstLineOcMsg:
2018-08-28 18:23:50.457 restore-symbol[22154:403912] Warning: Parsing method types failed, collectThreads:crashThread:resumedThreads:resumedThreadCount:

**Comment by kobe1941** [comment]
![image](https://user-images.githubusercontent.com/7099017/44722313-453fed80-aaff-11e8-9052-962e95f5a6df.png)
如图，OC符号已经恢复了，但是block符号还是不行，help...

**Comment by kobe1941** [comment]
当然因为脚本不能解析胖二进制，所以用的是lipo分离出来的arm64架构的二进制文件

**Comment by tobefuturer** [comment]
block符号的恢复步骤可以直接用原二进制，ida也会自动识别oc的函数符号。
block符号那一步，你看看用ida跑出来的json文件内容是啥

**Comment by kobe1941** [comment]
@tobefuturer json文件是类似如下这样子的：
 {
  "name": "-[QLAdClickReportHelper showSecondConfirmView]_block", 
  "address": "0x100340000"
 }, 

看起来问题不大，是不是我用的姿势有问题？导致二进制的地址对应不上？
我的操作流程是，把恢复了block符号的二进制文件，去替换ipa包里的二进制文件，然后用monkeyDev把APP安装到手机里，目测步骤好像是这样子的。。。

**Comment by tobefuturer** [comment]
看来是 搜索block的那个python脚本 没把那些block符号全找出来

**Comment by kobe1941** [comment]
大兄弟我遇到一个很诡异的问题。。
目标APP： 腾讯体育，按照流程走下来很顺利，然后我hook了一个函数，Xcode的堆栈只显示了两个相关的调用数据，而[NSThread callStackSymbols]可以找到好几个调用，为啥这个对不上号呢？
以下是截图：
![image](https://user-images.githubusercontent.com/7099017/47615684-e7268b00-daec-11e8-9ba4-61f0dc52f171.png)

另外就是，为何[NSThread callStackSymbols]里的堆栈信息，全是QQSportsV3，而不是具体的函数调用呢？

我看block_symbol.json文件应该是没什么问题的，函数名字和地址什么的都有列出来的

**Comment by tobefuturer** [comment]
你用 lldb的bt命令看看，我不确定[NSThread callStackSymbols]里面是怎么解析堆栈名称的，

**Comment by tobefuturer** [comment]
_ZN16AVDataParamVideo5cloneEPKS_ 那个 你仔细看 是 “ _ZN16AVDataParamVideo5cloneEPKS_ + 6517924” 有个很大的偏移，其实就是没找到符号的意思。。。。

**Comment by kobe1941** [comment]
哦哦，我再试试看

**Comment by kobe1941** [comment]
有个地方我可能没理解对，我用monkeyDev来运行我的APP，然后如果我如果加入了其他的代码或者第三方的库后，是不是提取block符号，需要重新再做一遍，而不是拿着源APP的二进制去IDA里分析？

**Comment by kobe1941** [comment]
monkeydev的工程在使用Xcode运行的时候，每次都会生成一个新的二进制文件，这个对提取block符号有影响嘛？

**Comment by kobe1941** [comment]
bt指令的确比NSThread靠谱多了，可以打印出OC的函数调用了~

**Comment by kobe1941** [comment]
用bt指令查看，block符号也顺利恢复了，感谢作者~

**Comment by CodeLife2012** [comment]
@tobefuturer 去哪工作了？

**Comment by wujianbotju** [comment]
> 用bt指令查看，block符号也顺利恢复了，感谢作者~

前辈，请教一下，为什么我用monkeydev，不管是手动先restore_symbol还是使用monkeydev项目自带的build_settings来恢复，即使用bt命令查看到的全都是___lldb_unnamed_symbol16283这种符号呢？(除了iOS系统的符号能正确显示以外，其他的都不行)

**Comment by kobe1941** [comment]
如果是单个APP不行的话，可能它做了混淆 @wujianbotju
