### ISSUE TITLE
restore-symbol 任一瘦架构的时候命中断言(参数错误)

### ISSUE THREAD

**Issue by yingkong1987** [tobefuturer/restore-symbol#26]
*** Assertion failure in -[CDObjectiveC2Processor loadClassAtAddress:], ~/restore-symbol/class-dump/Source/CDObjectiveC2Processor.m:258
2018-12-05 16:03:43.945 restore-symbol[887:6136039] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: moduleName.length == length'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff485f3e65 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7464f720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff4860eab2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff4a9b2d1d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   restore-symbol                      0x000000010f0f634b -[CDObjectiveC2Processor loadClassAtAddress:] + 2821
	5   restore-symbol                      0x000000010f0f3e4e -[CDObjectiveC2Processor loadClasses] + 243
	6   restore-symbol                      0x000000010f0f1158 -[CDObjectiveCProcessor process] + 391
	7   restore-symbol                      0x000000010f0de9aa -[CDClassDump processObjectiveCData] + 344
	8   restore-symbol                      0x000000010f0d3dff restore_symbol + 831
	9   restore-symbol                      0x000000010f0dbd36 main + 482
	10  libdyld.dylib                       0x00007fff7571e08d start + 1
	11  ???                                 0x0000000000000004 0x0 + 4
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    887 abort      ./restore-symbol Douban_arm64 -o Douban_64

**Comment by yingkong1987** [comment]
![1544000149692](https://user-images.githubusercontent.com/2038099/49501795-ae798e80-f8ae-11e8-8a71-59bc5401ebb3.jpg)
好像是针对Swift函数的截取判断有点问题

**Comment by tobefuturer** [comment]
估计是restore-symbol用的class-dump版本太旧了，你这是什么app，我有空的时候看下

**Comment by tobefuturer** [comment]
嗯 你用了哪个版本的class-dump覆盖的？
restore-symbol 里用git submodule引入class-dump，我覆盖一下就好，或者方便的话提个mr给我也行

**Comment by yingkong1987** [comment]
> 嗯 你用了哪个版本的class-dump覆盖的？
> restore-symbol 里用git submodule引入class-dump，我覆盖一下就好，或者方便的话提个mr给我也行

好的.我是看github上classdump的fork看到了原链接, 然后就替换了这一个函数. 
不过我看git submodule引入的dump库不是你的repo. merge上去估计要那个老外来审核了.

**Comment by tobefuturer** [comment]
你是直接用https://github.com/nygard/class-dump这个原始仓库master分支的最新代码 覆盖的？
是的话 我直接让restore-symbol引用这个仓库就好

**Comment by yingkong1987** [comment]
[0001-class-dumpSwift.patch.zip](https://github.com/tobefuturer/restore-symbol/files/2648165/0001-class-dumpSwift.patch.zip)

这个是我的patch. 你可以先看下,改动量不大. 建议还是不要改引用.

**Comment by yingkong1987** [comment]
> [0001-class-dumpSwift.patch.zip](https://github.com/tobefuturer/restore-symbol/files/2648165/0001-class-dumpSwift.patch.zip)
> 
> 这个是我的patch. 你可以先看下,改动量不大. 建议还是不要改引用.

或者你自己fork成自己的repo看看. 这样download下来的工程也不用担心要递归拉取了.
反正那个老外也已经4年多没更新了

**Comment by tobefuturer** [comment]
嗯，你这个patch是从哪个链接里来的？我怕swift还有别的坑，想着要不要直接换个class-dump的引用

**Comment by yingkong1987** [comment]
> 嗯，你这个patch是从哪个链接里来的？我怕swift还有别的坑，想着要不要直接换个class-dump的引用

可以试试原始仓库.

**Comment by tobefuturer** [comment]
嗯 thanks～ @yingkong1987

**Comment by MrGuys** [comment]
看了半天没整明白怎么解决。。。我也遇到这个问题，请问怎么解决呢。。。

**Comment by fly8888** [comment]
这个问题没有修复吗？

**Comment by crifan** [comment]
详见 #25 中我的回复：
https://github.com/tobefuturer/restore-symbol/issues/25#issuecomment-1101949480
