### ISSUE TITLE
how to use xcode and lldb debug alipay

### ISSUE THREAD

**Issue by a542343910** [tobefuturer/restore-symbol#5]
I want use Xcode and lldb debug ios apps like author, but don't know how to, thanks for help.

**Comment by tobefuturer** [comment]
https://github.com/tobefuturer/restore-symbol/issues/4
see answer on 2-floor

**Comment by CodeLife2012** [comment]
这个依赖于越狱的版本的，一般的越狱也没有释放这个权限...

**Comment by tobefuturer** [comment]
It doesn't depend on jailbreak environment， but the target app must be signed by development certificate。
