### ISSUE TITLE
恢复失败！！！

### ISSUE THREAD

**Issue by yuchuanfeng** [tobefuturer/restore-symbol#6]
./restore-symbol WeChat.app/WeChat  -o  WeChat_symbol
这样不对吗？

执行失败：
Restore-symbol supports armv7 and arm64 archtecture, but not support fat file. Please use lipo to thin the image file first.

**Comment by tobefuturer** [comment]
那句输出 就是错误提示。。。。

**Comment by yuchuanfeng** [comment]
不支持X86_64吗？什么原因导致失败的？？
