### ISSUE TITLE
恢复后在Xcode中调试不显示方法名

### ISSUE THREAD

**Issue by yuchuanfeng** [tobefuturer/restore-symbol#7]
用您提供的工具成功导出后用MachOView打开能找到方法名，但是在Xcode中调试还是不显示。
我是重签名后安装在非越狱手机上跑的。
![snip20161228_4](https://cloud.githubusercontent.com/assets/10720607/21514190/35ee33c8-ccfd-11e6-9bd4-558607f4aa43.png)
![snip20161228_5](https://cloud.githubusercontent.com/assets/10720607/21514192/3a32ad2e-ccfd-11e6-9b4c-25cd2ee9cf46.png)

**Comment by tobefuturer** [comment]
你看看 是不是同个地址有2个符号名 它显示了现在这个

杨君

**Comment by yuchuanfeng** [comment]
我在MachOView里面没有看到重复的地址呀，应该不是这个原因吧
![snip20161229_8](https://cloud.githubusercontent.com/assets/10720607/21536112/558aae3e-cdb9-11e6-8956-61cae2c33594.png)

另外在Xcode中，打断点的时候方法名也是显示__hidden#xx 但是有的地方能显示出方法名
![snip20161229_6](https://cloud.githubusercontent.com/assets/10720607/21536129/834ee664-cdb9-11e6-9cf1-fad35a860b4b.png)

**Comment by tobefuturer** [comment]
方便的话 能发我一下这个app吗 这么远程看我也看不到详细的情况

在 2016年12月29日 上午11:26，chuanfeng <notifications@github.com>写道：

**Comment by yuchuanfeng** [comment]
你好，其实这个app是我测试用的，我自己写的demo导出的adhoc包，然后用来测试恢复符号表。
文件给你发邮箱了。
有时间麻烦您看下，非常感谢。
