### ISSUE TITLE
如果是fat file，是分开还原再合并起来么?

### ISSUE THREAD

**Issue by YangZhou91** [tobefuturer/restore-symbol#8]
还原部落冲突

第一次用Clutch dump 出来binary， 然后restore-symbol 显示是fat file，然后lipo -thin armv7。 就可以restore了。

第二次用Clutch dump ipa 文件，然后把mach-o文件拷贝出来，显示无法识别architecture, 再次lipo， 然后restore，重签名。

然后安装，安装以后，游戏就卡在同意条款的地方，一直谈条款。所以如果是fat file 还要在用lipo 把armv7 和 arm64 打包回去。

**Comment by tobefuturer** [comment]
嗯 是的 如果是fat file就拆开再合回去，一般分析的时候   根据自己的设备和工具选一个版本就好 没必要两个架构同样的工作做两次

杨君
