### ISSUE TITLE
如何在 Xcode 中调试第三方应用

### ISSUE THREAD

**Issue by buginux** [tobefuturer/restore-symbol#9]
不好意思，因为我之前都是直接在控制台直接使用 lldb 远程动态调试的。看了博主的文章，直接在 Xcode 里面进行 lldb 调试还能直接看到调用栈，感觉很方便。

想请教下博主如何直接在 Xcode 里面对第三方应用进行调试呢？

**Comment by tobefuturer** [comment]
https://github.com/tobefuturer/restore-symbol/issues/4
see answer on 2-floor
